#!/bin/bash
#
# License: MIT
# Author: Benoit DOLEZ <bdolez@zenetys.com>
# Copyright: 2019
#

function usage() {
  local IFS=$'\t'
  exec >&2
  if [[ $0 == "-bash" ]] ; then return 1 ; fi
  (( $# > 0 )) && echo "ERROR: $*"
  version
  echo "Usage: ${0##*/} [options...] specfile|specdir"
  echo "Options:"
  sed -nr "s/^[[:space:]]*## ([^:]*): /\1\t/p" -- "$0" |
    while read OPT DESC ; do
      printf " %-24s %s\n" "$OPT" "$DESC"
    done
  echo
  return 0
}

function version() {
  local PROGFILE=$0
  local VERSION=$(sed -n 's/^# Version: //p' $PROGFILE)
  local AUTHOR=$(sed -n 's/^# Author: //p' $PROGFILE)
  local LICENSE=$(sed -n 's/^# License: //p' $PROGFILE)

  echo "${PROGFILE##*/}${VERSION:+ $VERSION} - $AUTHOR - $LICENSE"
}

function on_exit() {
  if [[ -n $GITREV && $SPECFILE == *.gitrev ]]; then
    rm -f "$SPECDIR/$SPECFILE"
  fi
  if [[ -n $GIT_ARCHIVE_TMP && -d $GIT_ARCHIVE_TMP ]]; then
    rm -rf "$GIT_ARCHIVE_TMP"
  fi
}

function fatal() {
  echo "FATAL: $*" >&2
  exit 1
}

trap on_exit EXIT

declare QUIET=$QUIET
declare VERBOSE=$VERBOSE
declare XDEBUG=$XDEBUG
declare ARGS=()

declare CACHEBASE=${CACHEBASE:-/tmp}
declare DIST=
declare REPO=$REPO
declare UPDATE=
declare KEEP=
declare NOKEEP=
declare GITREV=
declare SOURCEDIR=$SOURCEDIR
declare OUTPUTDIR=$OUTPUTDIR
declare PREBUILDSCRIPT=$PREBUILDSCRIPT
declare DOWNLOAD=1
declare SIGN=
declare GPG_KEYID=
declare GPG_SECRET_KEY_FILE=
declare GPG_SECRET_KEY=
declare GPG_PASSPHRASE_FILE=
declare GPG_PASSPHRASE_ENV=
declare GPG_HOMEDIR=${GNUPGHOME:-~/.gnupg}
declare RPMOPTS=()
declare RPMBUILDOPTS=()
declare RPMSPECOPTS=()

if [[ -n $VERBOSE ]] ; then
  ( IFS='' ; echo "[DEBUG] '${0}${*/#/' '}'" )
fi

while (( $# > 0 )); do
  case "$1" in
    ## -h, --help: This help
    -h|--help) usage && exit 0 ;;
    ## -V, --version: Show version
    -V|--version) version && exit 0 ;;
    ## --x-debug: Enable bash debug mode
    --x-debug)    XDEBUG=1 ;;
    ## -v, --verbose: Define verbose level (must be repeat)
    -v|--verbose) ((VERBOSE++)) ;;
    ## -d, --dist DIST: Define dist version (eg: el8)
    -d|--dist) DIST=$2 ; shift ;;
    ## -I, --image IMAGE: Build using a specific docker image
    -I|--image) IMAGE=$2 ; shift ;;
    ## -s, --source PATH: define source directory
    -s|--sourcedir) SOURCEDIR=${2%/} ; shift ;;
    ## -O, --outputdir PATH: define output directory for generated packages
    -O|--outputdir) OUTPUTDIR=${2%/} ; shift ;;
    ## --no-download: skip downloading sources if needed
    --no-download) DOWNLOAD=0 ;;
    ## --repo PATH: local repository
    --repo) REPO=$2 ; shift ;;
    ## --update: update repository with new packages
    --update) UPDATE=1 ;;
    ## --keep: keep build environment after build_ldflags
    --keep) KEEP=1; NOKEEP= ;;
    ## --nokeep: never keep build environment on error
    --nokeep) NOKEEP=1; KEEP= ;;
    ## --gitrev: create source0 tarball from git revision
    --gitrev) GITREV=$2 ; shift ;;
    ## --sign: enable rpm signing
    --sign) SIGN=1 ;;
    ## --gpg-homedir: path to gpg homedir
    --gpg-homedir) GPG_HOMEDIR=$2 ; shift ;;
    ## --gpg-keyid: gpg keyid for signing
    --gpg-keyid) GPG_KEYID=$2 ; shift ;;
    ## --gpg-secret-key-file: armored gpg secret key for signin
    --gpg-secret-key-file) GPG_SECRET_KEY_FILE=$2 ; shift ;;
    ## --gpg-passphrase-file: read key passphrase from file
    --gpg-passphrase-file) GPG_PASSPHRASE_FILE=$2 ; shift ;;
    ## --gpg-passphrase-env: read key passphrase from environment variable
    --gpg-passphrase-env) GPG_PASSPHRASE_ENV=$2 ; shift ;;
    # generic args
    --) shift ; break ;;
    -*) usage "Unknown parameter '$1'" && exit 1 ;;
    *) ARGS+=( "$1" ) ;;
  esac
  shift
done

[[ $XDEBUG == 1 ]] && set -x

RPMOPTS+=( "$@" )

declare SPECFILE=${ARGS[0]}
[[ ${SPECFILE:0:1} != "/" ]] && SPECFILE=$PWD/$SPECFILE

# cleanup potential trailing slashes
SPECFILE=${SPECFILE%${SPECFILE##*[!/]}}
[[ -r $SPECFILE ]] || fatal "Can't open $SPECFILE for reading"

if [[ -d $SPECFILE ]] ; then
  if [[ -d $SPECFILE/SPECS ]] ; then
    SPECFILE=( $SPECFILE/SPECS/*.spec )
  else
    SPECFILE=( $SPECFILE/*.spec )
  fi
  [[ ${#SPECFILE[@]} == 1 ]] || fatal "Undefined spec file: '${SPECFILE[*]}'"
fi

# define SPECDIR & SPECFILE from SPECFILE
SPECDIR=${SPECFILE%/*}
SPECFILE=${SPECFILE##*/}

if [[ -z $SOURCEDIR && -d ${SPECDIR%/*}/SOURCES ]] ; then
  SOURCEDIR=${SPECDIR%/*}/SOURCES
fi

if [[ -n $PREBUILDSCRIPT ]]; then
  [[ ${PREBUILDSCRIPT:0:1} == / ]] || PREBUILDSCRIPT="$PWD/$PREBUILDSCRIPT"
elif [[ -z $PREBUILDSCRIPT ]]; then
  # auto locate prebuild script if not given
  for dir in "$SPECDIR" "$PWD"; do
    for ext in sh inc; do
      if [[ -e "$dir/prebuild.$ext" ]]; then
        PREBUILDSCRIPT="$dir/prebuild.$ext"
        break 2
      fi
    done
  done
fi
if [[ -n $PREBUILDSCRIPT ]]; then
  [[ -r $PREBUILDSCRIPT ]] ||
    fatal "Can't open $PREBUILDSCRIPT for reading"
  [[ ${PREBUILDSCRIPT##*.} == .sh && ! -x $PREBUILDSCRIPT ]] &&
    fatal "Prebuild script $PREBUILDSCRIPT not executable"
fi

[[ -z $SOURCEDIR ]] && SOURCEDIR=$PWD
[[ -z $OUTPUTDIR ]] && OUTPUTDIR=$PWD
[[ ${SOURCEDIR:0:1} != "/" ]] && SOURCEDIR=$PWD/$SOURCEDIR
[[ ${OUTPUTDIR:0:1} != "/" ]] && OUTPUTDIR=$PWD/$OUTPUTDIR
[[ -n $REPO && ${REPO:0:1} != "/" ]] && REPO=$PWD/$REPO

if [[ -n $SIGN ]]; then
  if [[ -n $GPG_PASSPHRASE_FILE ]]; then
    [[ ${GPG_PASSPHRASE_FILE:0:1} != "/" ]] && GPG_PASSPHRASE_FILE="$PWD/$GPG_PASSPHRASE_FILE"
    [[ -r $GPG_PASSPHRASE_FILE ]] || fatal 'Cannot not read passphrase file'
  elif [[ -n $GPG_PASSPHRASE_ENV ]]; then
    export -n GPG_PASSPHRASE_ENV
  else
    echo -n 'Enter sign key passphrase: '
    { read -rs GPG_PASSPHRASE; ret=$?; echo; ((ret==0)); } || fatal 'Could not read passphrase'
    GPG_PASSPHRASE_ENV=GPG_PASSPHRASE
  fi
  if [[ -n $GPG_SECRET_KEY_FILE ]]; then
    [[ ${GPG_SECRET_KEY_FILE:0:1} != "/" ]] && GPG_SECRET_KEY_FILE="$PWD/$GPG_SECRET_KEY_FILE"
    if [[ -z $GPG_KEYID ]]; then
      GPG_KEYID=$(gpg --show-keys --with-colons "$GPG_SECRET_KEY_FILE" |
        awk -F : '$1=="sec"{getline;print $10;exit}')
      [[ -z $GPG_KEYID ]] && fatal 'Cannot read GPG keyid'
    fi
  else
    [[ -d $GPG_HOMEDIR ]] || fatal "GPG homedir $GPG_HOMEDIR not a directory"
    # select first secret key if none given
    if [[ -z $GPG_KEYID ]]; then
      GPG_KEYID=$(gpg --homedir "$GPG_HOMEDIR" --list-secret-keys --with-colons |
        awk -F : '$1=="sec"{getline;print $10;exit}')
      [[ -z $GPG_KEYID ]] && fatal 'Cannot guess GPG keyid'
    fi
    # export secret key
    GPG_SECRET_KEY=$(if [[ -n $GPG_PASSPHRASE_FILE ]]; then cat "$GPG_PASSPHRASE_FILE"
        else (set +x && echo "${!GPG_PASSPHRASE_ENV}"); fi |
      gpg --homedir "$GPG_HOMEDIR" --batch --passphrase-fd 0 --pinentry-mode loopback \
        --armor --export-secret-keys --with-fingerprint "$GPG_KEYID") ||
          fatal 'Failed to export GPG secret key'
  fi
fi

echo "SPECFILE: $SPECFILE"
echo "SPECDIR: $SPECDIR"
echo "SOURCEDIR: $SOURCEDIR"
echo "OUTPUTDIR: $OUTPUTDIR"
echo "PREBUILDSCRIPT: ${PREBUILDSCRIPT:-none}"
echo "REPO: ${REPO:-none}"
echo "SIGN: ${SIGN:-0}"

# Yum might take for ages to complete because it CLOEXEC on all available
# file descriptors and recent dockers sets a very high default limit.
# https://bugzilla.redhat.com/show_bug.cgi?id=1537564
# https://github.com/rpm-software-management/rpm/pull/444
DOCKER_OPTS_DIST_el6=( --ulimit 'nofile=1024' )
function dockerfile_for_dist_el6() {
  cat <<'EOF'
FROM centos:6
RUN set -x && \
    ulimit -n 1024 && \
    sed -i -re 's,mirror\.centos\.org,vault.centos.org,; s,^(mirrorlist),#\1,; s,^#(baseurl),\1,' /etc/yum.repos.d/CentOS-*.repo && \
    yum update -y && \
    yum install -y createrepo gcc make rpm-build && \
    echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf && \
    sed -r -i -e 's/^(keepcache)=.*/\1=1/' /etc/yum.conf && \
    yum install -y bzip2-devel db4-devel elfutils-devel elfutils-libelf-devel file-devel gawk gettext-devel libacl-devel libcap-devel libtool lua-devel ncurses-devel nss-devel nss-softokn-freebl-devel popt-devel python-devel readline-devel redhat-rpm-config xz-devel zlib-devel && \
    { curl -OL --connect-timeout 15 http://ftp.rpm.org/releases/rpm-4.11.x/rpm-4.11.3.tar.bz2 || \
      curl -OL --connect-timeout 15 http://ftp.lip6.fr/pub/linux/rpm/releases/rpm-4.11.x/rpm-4.11.3.tar.bz2; } && \
    tar xvjf rpm-4.11.3.tar.bz2 && \
    cd rpm-4.11.3 && \
    export CFLAGS=$(rpm -E '%{optflags}') && \
    export CPPFLAGS="$(pkg-config --cflags nss) -USYSCONFDIR -DSYSCONFDIR=\\\"/etc\\\" -ULOCALSTATEDIR -DLOCALSTATEDIR=\\\"/var\\\" -URPMCONFIGDIR -DRPMCONFIGDIR=\\\"/usr/lib/rpm\\\" -URPMCONFIGDIR -DRPMCONFIGDIR=\\\"/usr/lib/rpm\\\"" && \
    autoreconf -i && \
    ./configure --enable-static=yes --enable-shared=no --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --with-vendor=redhat --with-external-db --with-lua --with-cap --with-acl --without-selinux --disable-python --disable-plugins --disable-nls && \
    make && \
    cp -a rpmspec /usr/local/bin/ && \
    cd .. && \
    rm -rfv rpm-4.11.3.tar.bz2 rpm-4.11.3 && \
    yum history undo -y $(yum history |awk '$1 ~ /^[0-9]$/ { print $1; exit; }') && \
    yum clean all
EOF
}

# Yum might take for ages to complete because it CLOEXEC on all available
# file descriptors and recent dockers sets a very high default limit.
# https://bugzilla.redhat.com/show_bug.cgi?id=1537564
# https://github.com/rpm-software-management/rpm/pull/444
DOCKER_OPTS_DIST_el7=( --ulimit 'nofile=1024' )
function dockerfile_for_dist_el7() {
  cat <<'EOF'
FROM centos:7
RUN set -x && \
    ulimit -n 1024 && \
    sed -i -re 's,mirror\.centos\.org,vault.centos.org,; s,^(mirrorlist),#\1,; s,^#(baseurl),\1,' /etc/yum.repos.d/CentOS-*.repo && \
    yum update -y && \
    yum install -y createrepo gcc make rpm-build && \
    echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf && \
    sed -r -i -e 's/^(keepcache)=.*/\1=1/' /etc/yum.conf && \
    yum clean all
EOF
}

function dockerfile_for_dist_el8() {
  cat <<'EOF'
FROM rockylinux:8
RUN set -x && \
    yum update -y && \
    yum install -y createrepo gcc make rpm-build && \
    echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf && \
    echo keepcache=1 >> /etc/yum.conf && \
    echo keepcache=1 >> /etc/dnf/dnf.conf && \
    sed -i -re s,enabled=0,enabled=1, /etc/yum.repos.d/Rocky-PowerTools.repo && \
    yum clean all
EOF
}

# Lookup "docker build" source to build a base image for $DIST.
function dockerfile_for_dist() {
  if [[ -f ~/.config/${0##*/}/Dockerfile.$DIST ]]; then
    cat ~/.config/"${0##*/}/Dockerfile.$DIST"
  elif declare -f -F "dockerfile_for_dist_$DIST" >/dev/null; then
    "dockerfile_for_dist_$DIST"
  else
    return 1
  fi
}

# normal dockerfile method may work with recent distro/docker
DOCKER_OPTS_DIST_el9=( --security-opt seccomp=unconfined )
function dockerscript_for_dist_el9() {
  IMAGE=$1; shift
  echo "# Build $IMAGE..."
  set -xe
  id=$(docker run "$@" -d ${DOCKER_HUB_IMAGE:-rockylinux:9} sleep infinity)
  docker exec "$id" dnf update -y
  docker exec "$id" dnf install -y createrepo gcc make rpm-build
  docker exec "$id" sh -c "echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf"
  docker exec "$id" sh -c "echo keepcache=1 >> /etc/dnf/dnf.conf"
  docker exec "$id" sh -c $'awk \x27/^\[/ { inside=$1 } inside=="[crb]"&&/enabled/{print "enabled=1"; next}{print}\x27 /etc/yum.repos.d/rocky.repo > /etc/yum.repos.d/rocky.repo.new && mv /etc/yum.repos.d/rocky.repo{.new,}'
  docker exec "$id" dnf clean all
  docker container commit "$id" "$IMAGE"
  docker kill "$id"
  docker rm "$id"
}

# normal dockerfile method may work with recent distro/docker
DOCKER_OPTS_DIST_el10=( --security-opt seccomp=unconfined )
DOCKERSCRIPT_ENV_for_el10=$(declare -f dockerscript_for_dist_el9)
function dockerscript_for_dist_el10() {
  DOCKER_HUB_IMAGE='rockylinux/rockylinux:10' \
    dockerscript_for_dist_el9 "$@"
}

# Lookup docker script source to build a base image for $DIST.
function dockerscript_for_dist() {
  if [[ -f ~/.config/${0##*/}/build-image.$DIST ]]; then
    cat ~/.config/"${0##*/}/build-image.$DIST"
  elif declare -f "dockerscript_for_dist_$DIST"; then
    local env_ref="DOCKERSCRIPT_ENV_for_$DIST"
    [[ -n ${!env_ref} ]] && echo "$DOCKERSCRIPT_ENV_for_el10"
    echo "'dockerscript_for_dist_$DIST' \"\$@\""
  else
    return 1
  fi
}

if [[ -f ~/.config/"${0##*/}/before-image.hook" ]] &&
   ! source ~/.config/"${0##*/}/before-image.hook"; then
  fatal 'Failed to source before-image.hook'
fi

DOCKER_OPTS_DIST="DOCKER_OPTS_DIST_$DIST[@]"
DOCKER_OPTS_DIST=( "${!DOCKER_OPTS_DIST}" )

if [[ -z $IMAGE ]]; then
  [[ -z $DIST ]] && fatal 'Require -d DIST or -I IMAGE (or both)'
  # Set $IMAGE from $DIST
  image_src=; image_script=;
  if ! image_src=$(dockerfile_for_dist) &&
     ! image_script=$(dockerscript_for_dist); then
    fatal "No image source for $DIST"
  fi
  image_sig=$(echo "${image_src:-$image_script}" |md5sum |sed -re 's,^(.{7}).*,\1,')
  IMAGE="rpmbuild/$DIST:$image_sig"
  if ! docker images -q "$IMAGE" |grep -q .; then
    # Build docker image
    if [[ -n $image_src ]] && ! echo "$image_src" |docker build -t "$IMAGE" -; then
      fatal "Failed to build image $IMAGE for $DIST"
    elif ! echo "$image_script" |bash -s -- "$IMAGE" "${DOCKER_OPTS_DIST[@]}"; then
      fatal "Image $IMAGE for $DIST, build scripit failed"
    fi
  fi
elif [[ -z $DIST ]]; then
  # Set $DIST from $IMAGE
  DIST=$(docker run --rm "$IMAGE" rpm -E '%{dist}' |sed 's,^\.\+,,')
  [[ -z $DIST ]] && fatal "Failed to identify dist in image $IMAGE"
fi

if [[ -f ~/.config/"${0##*/}/after-image.hook" ]] &&
   ! source ~/.config/"${0##*/}/after-image.hook"; then
  fatal "Failed to source after-image.hook"
fi

# Extract type and version from $DIST for convenience
DIST_VERSION=${DIST##*[!0-9]}
DIST_TYPE=${DIST%$DIST_VERSION}

echo "DIST: $DIST"
echo "DIST_TYPE: $DIST_TYPE"
echo "DIST_VERSION: $DIST_VERSION"
echo "IMAGE: $IMAGE"

# Create missing directories
for i in "$CACHEBASE"/cache-{yum-"$DIST",shared} \
         "$OUTPUTDIR"/{RPMS,SRPMS} \
         ${REPO:+"$REPO"}; do
  [[ ! -d $i ]] && ! mkdir -p "$i" && fatal "Cannot create directory: $i"
done

# Need rpmbuild --noclean option to keep generated files in place
if [[ $DIST_TYPE == el && $DIST_VERSION -ge 7 ]] ||
   docker run --rm "${DOCKER_OPTS_DIST[@]}" "$IMAGE" rpm --noclean >/dev/null 2>&1
then
  RPMBUILDOPTS+=( --noclean )
fi

# Prepare env and script to be run inside the container
BGROUP=$(id -gn)
BUSER=${USER:-$(id -un)}
BHOME=~

# Handle $GITREV:
# - create a source tarball from the current directory, assuming it is a git
# - use it as source0
# - change version accordingly (git describe) in spec file

# $1: git rev
# $2: output filename without extension (.tar.gz auto added)
# $3: prefix without trailing slash
function git_archive_mtime() {
  GIT_ARCHIVE_TMP=$(mktemp -d) || return 1
  git archive --format tar --prefix "$3/" \
    "$1" ./ ':!rpmbuild-docker' ':!*.spec' ':!SPECS/' |
    tar x -C "$GIT_ARCHIVE_TMP/" || return 1
  find "$GIT_ARCHIVE_TMP/$3/" -not -type d -printf '%P\n' |
    xargs -n 1 -I{} sh -c 'touch -d "$(git log --pretty=format:%ci -n 1 "$1" -- "$3")" "$2/$3"' -- \
      "$1" "$GIT_ARCHIVE_TMP/$3/" {} || return 1
  tar czf "$2.tar.gz" -C "$GIT_ARCHIVE_TMP/" "$3"
}

function gitrev2rpm() {
  local gitdesc gitdate
  gitdesc=$(git describe --tags --match 'v?*' --abbrev=7 --always "$1")
  if [[ $gitdesc =~ ^(v(.+)(-[0-9]+-g))?([0-9a-f]+)$ ]]; then
    gitdate=$(date -d "$(git log -n 1 --format='%ci' "$1")" +%Y%m%d%H%M%S)
    REPLY=( "${BASH_REMATCH[2]:-0.0.0}^${gitdate}g${BASH_REMATCH[4]}.${BUSER:0:3}" "${BASH_REMATCH[4]}" )
  else
    REPLY=( "${gitdesc:1}" "${gitdesc:1}" )
  fi
}

if [[ -n $GITREV ]]; then
  gitrev2rpm "$GITREV"
  project=${PWD##*/}
  sed -re "s,(^\\s*Version\\s*:\\s*).*,\\1${REPLY[0]}," \
    -e "s|(^\\s*source0\\s*:\\s*).*|\\1$project-dev.tar.gz|i" \
    "$SPECDIR/$SPECFILE" > "$SPECDIR/$SPECFILE.gitrev"
  SPECFILE="$SPECFILE.gitrev"
  git_archive_mtime "$GITREV" "$SOURCEDIR/$project-dev" "$project-${REPLY[1]}"
fi

# Options for docker
DOCKER_OPTS=(
  "${DOCKER_OPTS_DIST[@]}"
  --tmpfs /tmp:rw,exec
  --mount "type=bind,src=$SPECDIR/$SPECFILE,dst=/tmp/$SPECFILE"
  --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/yum"
  --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/dnf"
  --mount "type=bind,src=$CACHEBASE/cache-shared,dst=/tmp/cache-shared"
  --mount "type=bind,src=$SOURCEDIR,dst=/tmp/shared/SOURCES"
  --mount "type=bind,src=$OUTPUTDIR/SRPMS,dst=/tmp/shared/SRPMS"
  --mount "type=bind,src=$OUTPUTDIR/RPMS,dst=/tmp/shared/RPMS"
  ${GPG_PASSPHRASE_FILE:+--mount "type=bind,src=$GPG_PASSPHRASE_FILE,dst=/dev/shm/.p,ro"}
  ${GPG_SECRET_KEY_FILE:+--mount "type=bind,src=$GPG_SECRET_KEY_FILE,dst=/dev/shm/k,ro"}
  ${REPO:+--mount "type=bind,src=$REPO,dst=/tmp/local-repo"}
  ${PREBUILDSCRIPT:+--mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/${PREBUILDSCRIPT##*/}"}
)

function build_exit() {
  local status=${?:-0}
  [[ -n $NOKEEP ]] && exit "$status"
  [[ -n $KEEP || $status != 0 ]] && sleep infinity
  exit "$status"
}
function build_runuser() {
  local cmd
  printf -v cmd '%q ' "$@"
  runuser -l "$BUSER" -c "$cmd"
}
function build_dl() {
  local curlopts=( -fRL --connect-timeout 15 ) url=$1 dest=${2:-$CACHEDIR} retval
  if [[ $url =~ ^([^#]+)(#?)/([^/]+)$ ]]; then
    [[ -f $dest/${BASH_REMATCH[3]} ]] && return 0
    [[ ${BASH_REMATCH[2]} == '#' ]] && url=${BASH_REMATCH[1]}
    ${RUNUSER:+build_runuser} \
      curl "${curlopts[@]}" -o "$dest/${BASH_REMATCH[3]}" "$url"
    retval=$?
    REPLY="cURL return code $retval"
    return "$retval"
  else
    REPLY='URL not supported'
    return 1
  fi
}
function build_main() {
  set -fxe
  trap build_exit EXIT
  OIFS=$IFS

  mkdir -p -m 700 "$BHOME"
  chown "$BUSER:$BGROUP" "$BHOME"

  if [[ -n $SIGN ]]; then
    signreq=()
    for i in rpm-sign gnupg2; do rpm -q "$i" || signreq+=( "$i" ); done
    [[ -n $signreq ]] && yum install -y "${signreq[@]}"
    build_runuser mkdir -m 700 /dev/shm/g
    build_runuser ln -sT /dev/shm/g "$BHOME/.gnupg"
    build_runuser sh -exc 'GPG_TTY= gpg --passphrase-file /dev/shm/.p \
      --pinentry-mode loopback --import /dev/shm/k'
  fi

  mkdir /tmp/build
  chown "$BUSER:$BGROUP" /tmp/{build,shared}
  ln -s ../shared/SOURCES /tmp/build/

  if [[ -n "$REPO" ]]; then
    cat >/etc/yum.repos.d/local-repo.repo <<'EOF'
[local-repo]
name=local-repo
baseurl=file:///tmp/local-repo/RPMS
enabled=1
gpgcheck=0
EOF
    if [[ ! -d /tmp/local-repo/RPMS/repodata ]]; then
      build_runuser mkdir -p /tmp/local-repo/RPMS
      build_runuser createrepo /tmp/local-repo/RPMS
    fi
  fi

  if [[ -n $PREBUILDSCRIPT ]]; then
    case "$PREBUILDSCRIPT" in
      *.sh) "/tmp/$PREBUILDSCRIPT" ;;
      *.inc) source "/tmp/$PREBUILDSCRIPT" ;;
      *) echo 'Invalid prebuild script/source file'; exit 1 ;;
    esac
  fi

  # Having _topdir /tmp causes problems in el6/el7 because it is not long enough
  # https://access.redhat.com/solutions/1426113
  RPMOPTS+=(  --define '_topdir /tmp/../tmp/../tmp/build' )
  rpmbuildopts=( "${RPMOPTS[@]}" "${RPMBUILDOPTS[@]}" )
  rpmspecopts=( "${RPMOPTS[@]}" "${RPMSPECOPTS[@]}" )

  IFS=$'\n'
  buildreq=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
    sed -ne 's/^BuildRequires: *//p' |
    sed -re 's/(( +[^ ,]|[^ ,])*),/\1\n/g' |
    sed -re 's/^ *([^ ]( +[^ ]|[^ ])*) *$/\1/') )
  IFS=$OIFS
  if [[ -n $buildreq ]]; then
    yum install -y "${buildreq[@]}"
  fi

  # download sources if needed
  if [[ $DOWNLOAD == 1 ]] ; then
    dlsources=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
      sed -nr -e 's,^(source|patch)[0-9]*\s*:\s*(\S+).*,\2,i;T;/:\/\//p') )
    for i in "${dlsources[@]}"; do
        RUNUSER=1 build_dl "$i" /tmp/shared/SOURCES
    done
  fi

  build_runuser rpmbuild "${rpmbuildopts[@]}" -ba "/tmp/$SPECFILE"

  if [[ -n $SIGN ]]; then
    rpms=( $(find /tmp/build/{RPMS,SRPMS} -type f -name '*.rpm') )
    if [[ -n $rpms ]]; then
      build_runuser sh -exc 'GPG_TTY= rpm \
        --define "_gpg_sign_cmd_extra_args --passphrase-file /dev/shm/.p --pinentry-mode loopback" \
        --define "_gpg_name $1" --addsign "${@:2}"' -- "$GPG_KEYID" "${rpms[@]}"
    fi
  fi

  for repo in RPMS SRPMS; do
    build_runuser cp -aT "/tmp/build/$repo/" "/tmp/shared/$repo/"

    if [[ -n $REPO && -n $UPDATE ]] ; then
      build_runuser cp -aT "/tmp/build/$repo/" "/tmp/local-repo/$repo/"
      build_runuser createrepo --update "/tmp/local-repo/$repo"
    fi
  done
}

# Build RPM in the container
CTNAME="build_${RANDOM}${RANDOM}${RANDOM}${RANDOM}"
DOCKER_OPTS+=( --name "$CTNAME" -i --rm )
trap 'docker kill "$CTNAME"; exit;' INT
cat <<__EOF__ |docker run "${DOCKER_OPTS[@]}" "$IMAGE" /bin/bash &
declare -p HOSTNAME
$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP REPO RPMOPTS RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE SIGN GPG_KEYID)
echo "$(getent group "$BGROUP")" >> /etc/group
echo "$(getent passwd "$BUSER")" >> /etc/passwd
${GPG_SECRET_KEY:+(umask 0277 && (set +x && echo $(printf '%q\n' "$GPG_SECRET_KEY")) > /dev/shm/k && chown "\$BUSER" /dev/shm/k)}
${GPG_PASSPHRASE_ENV:+(umask 0277 && (set +x && echo $(printf '%q\n' "${!GPG_PASSPHRASE_ENV}")) > /dev/shm/.p && chown "\$BUSER" /dev/shm/.p)}
$(printf 'PREBUILDSCRIPT=%q\n' "${PREBUILDSCRIPT##*/}")
$(declare -f build_exit)
$(declare -f build_runuser)
$(declare -f build_dl)
$(declare -f build_main)
# exports for prebuild script
export -f build_dl build_runuser
export CACHEDIR=/tmp/cache-shared DIST DIST_TYPE DIST_VERSION
build_main
__EOF__
wait "$!"
